# Generated by Django 2.0 on 2018-01-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='task',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
